columnSuffix: iuayvltq
contentColumnType: text
fieldGroup: 78840b1d-1f21-4fcd-9e8e-55e548a9cd55 # Towns
handle: townLocation
instructions: 'Add latitude and longitude.'
name: 'Town Location'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
