fieldLayouts:
  b85ca0fd-90ba-4aee-b14d-e1e398142ecc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f16061bc-270f-493e-b8f6-d7d73581b9ab # Site Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f79d9aee-a655-4424-a173-6cfd634fa693
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f2334ff-7130-4b9e-8952-078e6e8f9f28
        userCondition: null
handle: siteHero
name: 'Site Hero'
sortOrder: 1
