defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  2e8a3caf-58d4-45ef-adc2-f98e74401789: # Craft Project
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
